[package]
name = "yana"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28"
pulldown-cmark = "0.12.2"
ratatui = "0.29.0"
serde = {version = "1.0.216", features = ["derive"]}
serde_json = "1.0.133"


